/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData dizzy =
      IconData(0xf567, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown_open =
      IconData(0xf57a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grin_squint =
      IconData(0xf585, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meh_rolling_eyes =
      IconData(0xf5a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile_beam =
      IconData(0xf5b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
